# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('food', models.TextField()),
                ('birthdate', models.DateTimeField()),
                ('adoptdate', models.DateTimeField(blank=True, null=True)),
                ('ownes', models.TextField()),
            ],
        ),
    ]
